In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r"C:\Users\tamil\nlp-tutorials-main\9_bag_of_words\spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [3]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [4]:
df['spam'] = df['Category'].apply(lambda x: 1 if x =='spam' else 0)

In [6]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [7]:
df.shape

(5572, 3)

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

In [9]:
X_train.shape

(4457,)

In [10]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<4457x7717 sparse matrix of type '<class 'numpy.int64'>'
	with 58818 stored elements in Compressed Sparse Row format>

In [11]:
X_train_cv.toarray()[:2][0]


array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [12]:
X_train_cv.shape

(4457, 7717)

In [13]:
v.get_feature_names_out()[1771]

'chex'

In [14]:
v.vocabulary_

{'no': 4789,
 'we': 7396,
 'sell': 6000,
 'it': 3763,
 'all': 911,
 'so': 6276,
 'll': 4161,
 'have': 3355,
 'tons': 6963,
 'if': 3606,
 'coins': 1879,
 'then': 6820,
 'our': 5004,
 'to': 6925,
 'someone': 6295,
 'thru': 6869,
 'paypal': 5122,
 'voila': 7300,
 'money': 4563,
 'back': 1198,
 'in': 3645,
 'life': 4101,
 'pockets': 5280,
 'its': 3768,
 'not': 4822,
 'specialisation': 6361,
 'can': 1628,
 'work': 7567,
 'but': 1577,
 'slave': 6211,
 'labor': 3991,
 'will': 7498,
 'look': 4195,
 'for': 2929,
 'this': 6847,
 'month': 4571,
 'sha': 6049,
 'cos': 2010,
 'shakara': 6054,
 'beggar': 1299,
 'know': 3958,
 'she': 6073,
 'called': 1612,
 'me': 4400,
 'please': 5251,
 'leave': 4062,
 'topic': 6973,
 'sorry': 6325,
 'telling': 6748,
 'that': 6805,
 'comin': 1906,
 'fetch': 2807,
 'us': 7197,
 'oredi': 4981,
 'error': 2620,
 'probably': 5430,
 'worries': 7577,
 'things': 6837,
 'are': 1052,
 'coming': 1907,
 'due': 2474,
 'and': 962,
 'several': 6041,
 'outstanding': 5019,
 'invoices'

In [15]:
X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [16]:
np.where(X_train_np[0]!=0)

(array([ 911, 1198, 1879, 3355, 3606, 3645, 3763, 4101, 4161, 4563, 4789,
        5004, 5122, 5280, 6000, 6276, 6295, 6820, 6869, 6925, 6963, 7300,
        7396], dtype=int64),)

In [17]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [18]:
X_test_cv = v.transform(X_test)

In [19]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       968
           1       0.98      0.92      0.95       147

    accuracy                           0.99      1115
   macro avg       0.98      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115



In [20]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1], dtype=int64)

In [21]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [22]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [23]:
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       968
           1       0.98      0.92      0.95       147

    accuracy                           0.99      1115
   macro avg       0.98      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115

